name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Terraform Init
        run: terraform -chdir=terraform init

      
      - name: Terraform destroy
        run: terraform -chdir=terraform destroy -auto-approve


      - name: tfsec - Terraform Static Analysis
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Checkov - IaC Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:  
          TF_VAR_db_user: ${{ secrets.DB_USERNAME}}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}